"""
Task: transcribe_manga
Pool: vision
Purpose: Transcribe dialogue from manga gallery content based on reasoning and descriptions.
Input:
    metadata      dict  gallery metadata including title and tags
    dep_*         dict  summarize_manga output containing reasoning_text and descriptions
    url_slug      str   url slug (mandatory)
Output:
    transcript_text str  generated dialogue transcript
    reasoning_text  str  pass-through reasoning generated by the LLM
    start_page      int  starting page number
    url_slug        str  url slug (mandatory)
Creates: nothing
"""

import logging
from typing import Dict, Any

from modules.task_manager.task_manager import Task

log = logging.getLogger('task_transcribe_manga')
POOL = "vision"


async def run(task: Task, context: Dict[str, Any], input_data: Dict[str, Any]) -> Dict[str, Any]:
    url_slug = input_data["url_slug"]
    log.info(f"Starting transcribe_manga for slug: {url_slug}")

    try:
        metadata = input_data['metadata']

        # Extract reasoning_text and descriptions from dep_ enrichment
        reasoning_text = None
        descriptions = None
        
        for k, v in input_data.items():
            if k.startswith('dep_') and isinstance(v, dict):
                if 'reasoning_text' in v and 'descriptions' in v:
                    reasoning_text = v['reasoning_text']
                    descriptions = v['descriptions']
                    break
        
        if reasoning_text is None or descriptions is None:
            raise ValueError("Could not find 'reasoning_text' and 'descriptions' in dep_ enrichment")

        title_obj = metadata.get('title', {})
        titles_str = (
            title_obj.get('japanese') or 
            title_obj.get('pretty') or 
            title_obj.get('english') or 
            'Unknown'
        )
        tags_str = ', '.join(
            [t.get('name', '') for t in metadata.get('tags', [])]
        )

        # Sort descriptions by start_page to maintain order
        description_dicts = sorted(
            descriptions, key=lambda x: x.get('start_page', 0)
        )

        # Construct content body for prompt
        body_parts = []
        for d in description_dicts:
            body_parts.append(
                f"## Page {d['start_page']}-{d['end_page']}\n{d['description']}"
            )
        content_body = '\n\n'.join(body_parts)

        log.info(
            f'Transcribing: {titles_str} | '
            f'{len(description_dicts)} descriptions'
        )

        prompt_cfg = context['config']['prompts']['manga_transcribe']
        transcript_msg = prompt_cfg['user_template'].format(
            reasoning_text=reasoning_text,
            title=titles_str,
            tags=tags_str,
            content_body=content_body,
            instructions=prompt_cfg['instructions'],
        )

        from modules.llm_openai import chat
        system_msg = prompt_cfg['system']
        # Get max_tokens from config if available, otherwise use a large default
        manga_config = context['config'].get('manga', {})
        max_tokens = manga_config.get('transcription_max_tokens') or \
                     manga_config.get('vision_max_tokens') or 4096

        transcript = await chat(
            prompt=transcript_msg,
            system_prompt=system_msg,
            temperature=1.0,
            config=context['config'],
            max_tokens=max_tokens
        )
        log.info(f'Transcript preview: {transcript[:50]}')

        if not transcript:
            log.error('No transcript generated from LLM.')
            raise ValueError('No transcript generated from LLM.')

        return {
            'transcript_text': transcript,
            'reasoning_text': reasoning_text,
            'start_page': description_dicts[0]['start_page'] if description_dicts else 0,
            'url_slug': url_slug
        }
    except Exception as e:
        log.error(f"Task transcribe_manga failed: {e}")
        raise
